name: Release
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - shell: bash
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: |
        yarn deploy -p $VSCE_PAT
