name: Release
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: node:10-jessie
    steps:
      - uses: actions/checkout@v2
      - name: Install and build
        run: |
          yarn --frozen-lockfile
          yarn compile
        env:
          CI: true
      - name: Publish with vsce
        run: |
          yarn deploy -p $VSCE_PAT
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
